// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import elkfed.ml.util.Alphabet;
import exml.objects.*;

public class TuebaNESchema extends ObjectSchema<TuebaNEMarkable>
    {
        public static class TuebaNEFactory
          implements GenericObjectFactory<TuebaNEMarkable>
        {
            public TuebaNEMarkable createObject(ObjectSchema<TuebaNEMarkable> schema)
            {
                return new TuebaNEMarkable();
            }
        }
        public static TuebaNEFactory factory=new TuebaNEFactory();
        public static final Alphabet<String> global_alph=new Alphabet<String>();
        public static final Attribute<TuebaNEMarkable, String> ATTR_kind = new Attribute<TuebaNEMarkable, String> ("type",
                new IAccessor<TuebaNEMarkable, String>() {
                    public String get(TuebaNEMarkable o) {
                       return o.getKind(); }
                    public void put(TuebaNEMarkable o, String v) {
                       o.setKind(v); }},
                new EnumConverter());
        public static final TuebaNESchema instance=new TuebaNESchema();


        public TuebaNESchema() {
            super("ne", TuebaNEMarkable.class,
                  factory, global_alph);
            addAttribute(ATTR_kind);
        }
}