// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import elkfed.ml.util.Alphabet;
import exml.objects.ObjectSchema;
import exml.objects.NamedObject;
import exml.objects.GenericObjectFactory;
import exml.objects.StringConverter;
import exml.objects.ReferenceConverter;
import exml.objects.GenericAccessor;

public class TuebaEduSchema extends ObjectSchema<TuebaEduMarkable>
    {
        public static class TuebaEduFactory
          implements GenericObjectFactory<TuebaEduMarkable>
        {
            public TuebaEduMarkable createObject(ObjectSchema<TuebaEduMarkable> schema)
            {
                return new TuebaEduMarkable();
            }
        }
        public static TuebaEduFactory factory=new TuebaEduFactory();
        public static final Alphabet<String> global_alph=new Alphabet<String>();
        public static final int IDX_discRel=global_alph.lookupIndex("discRel");
        public static final TuebaEduSchema instance=new TuebaEduSchema();


        public TuebaEduSchema() {
            super("edu",factory,global_alph);
            addRelation("discRel", TuebaDiscRelSchema.instance);
        }

}