// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import elkfed.ml.util.Alphabet;
import exml.objects.GenericAccessor;
import exml.objects.GenericObjectFactory;
import exml.objects.NamedObject;
import exml.objects.ObjectSchema;
import exml.objects.ReferenceConverter;
import exml.objects.StringConverter;

public class TuebaSecEdgeSchema extends ObjectSchema<TuebaSecEdgeEdge>
    {
        public static class TuebaSecEdgeFactory
          implements GenericObjectFactory<TuebaSecEdgeEdge>
        {
            public TuebaSecEdgeEdge createObject(ObjectSchema<TuebaSecEdgeEdge> schema)
            {
                return new TuebaSecEdgeEdge();
            }
        }
        public static TuebaSecEdgeFactory factory=new TuebaSecEdgeFactory();
        public static final Alphabet<String> global_alph=new Alphabet<String>();
        public static final int IDX_cat=global_alph.lookupIndex("cat");
        public static final int IDX_parent=global_alph.lookupIndex("parent");
        public static final TuebaSecEdgeSchema instance=new TuebaSecEdgeSchema();


        public TuebaSecEdgeSchema() {
            super("secEdge",factory,global_alph);
            addAttribute("cat", new StringConverter(),
                         new GenericAccessor<TuebaSecEdgeEdge,String>(IDX_cat));
            addAttribute("parent", new ReferenceConverter(),
                         new GenericAccessor<TuebaSecEdgeEdge,NamedObject>(IDX_parent));
        }

}