// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import exml.objects.GenericObject;
import exml.objects.NamedObject;
import exml.annotations.MarkableSchema;

@MarkableSchema(TuebaDiscRelSchema.class)
public class TuebaDiscRelEdge extends GenericObject {
    public TuebaDiscRelEdge() {
        super(TuebaDiscRelSchema.instance.slotnames);
    }
    private String _relation;
    private String _marking;
    private NamedObject _arg2;
    public String getRelation() {
        return _relation;
    }

    public void setRelation(String val) {
        _relation = val;
    }
    public String getMarking() {
        return _marking;
    }

    public void setMarking(String val) {
        _marking = val;
    }
    public NamedObject getArg2() {
        return _arg2;
    }

    public void setArg2(NamedObject val) {
        _arg2 = val;
    }
}