// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import exml.objects.GenericObjectFactory;
import exml.objects.ObjectSchema;

public class TuebaTerminalSchema extends ObjectSchema<TuebaTerminal>
    {
        public static class TuebaTerminalFactory
            implements GenericObjectFactory<TuebaTerminal>
        {
            public TuebaTerminal createObject(ObjectSchema<TuebaTerminal> schema)
            {
                return new TuebaTerminal();
            }
        }
        public static TuebaTerminalFactory factory=new TuebaTerminalFactory();

        public static final TuebaTerminalSchema instance=new TuebaTerminalSchema();
        
        public static final int IDX_word=instance.slotnames.lookupIndex("form");
        
        public static final int IDX_cat=instance.slotnames.lookupIndex("pos");
        
        public static final int IDX_morph=instance.slotnames.lookupIndex("morph");
        
        public static final int IDX_lemma=instance.slotnames.lookupIndex("lemma");
        
        public static final int IDX_edge_label=instance.slotnames.lookupIndex("func");
        
        public static final int IDX_parent=instance.slotnames.lookupIndex("parent");
        
        public static final int IDX_wsd_lexunits=instance.slotnames.lookupIndex("wsd-lexunits");
        
        public static final int IDX_wsd_comment=instance.slotnames.lookupIndex("wsd-comment");
        
        public static final int IDX_syn_parent=instance.slotnames.lookupIndex("dephead");
        
        public static final int IDX_syn_label=instance.slotnames.lookupIndex("deprel");
        
        public static final int IDX_comment=instance.slotnames.lookupIndex("comment");
        

        public TuebaTerminalSchema() {
            super("word",factory);
        }

}