// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import elkfed.ml.util.Alphabet;
import exml.objects.ObjectSchema;
import exml.objects.NamedObject;
import exml.objects.GenericObjectFactory;
import exml.objects.StringConverter;
import exml.objects.ReferenceConverter;
import exml.objects.GenericAccessor;
import exml.objects.IAccessor;

public class TuebaTextSchema extends ObjectSchema<TuebaTextMarkable>
    {
        public static class TuebaTextFactory
          implements GenericObjectFactory<TuebaTextMarkable>
        {
            public TuebaTextMarkable createObject(ObjectSchema<TuebaTextMarkable> schema)
            {
                return new TuebaTextMarkable();
            }
        }
        public static TuebaTextFactory factory=new TuebaTextFactory();
        public static final Alphabet<String> global_alph=new Alphabet<String>();
        public static final TuebaTextSchema instance=new TuebaTextSchema();


        public TuebaTextSchema() {
            super("text", TuebaTextMarkable.class,
                  factory, global_alph);
            addAttribute("origin", new StringConverter(),
                new IAccessor<TuebaTextMarkable, String>() {
                    public String get(TuebaTextMarkable o) {
                       return o.getOrigin(); }
                    public void put(TuebaTextMarkable o, String v) {
                       o.setOrigin(v); }});
        }
}