// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import exml.objects.GenericObject;
import exml.objects.NamedObject;
import exml.annotations.MarkableSchema;

@MarkableSchema(TuebaConnectiveSchema.class)
public class TuebaConnectiveEdge extends GenericObject {
    public TuebaConnectiveEdge() {
        super(TuebaConnectiveSchema.instance.slotnames);
    }
    private String _konn;
    private String _rel1;
    private String _rel2;
    public String getKonn() {
        return _konn;
    }

    public void setKonn(String val) {
        _konn = val;
    }
    public String getRel1() {
        return _rel1;
    }

    public void setRel1(String val) {
        _rel1 = val;
    }
    public String getRel2() {
        return _rel2;
    }

    public void setRel2(String val) {
        _rel2 = val;
    }
}