// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import exml.GenericTerminal;
import exml.objects.NamedObject;

public class TuebaTerminal extends GenericTerminal {
    public TuebaTerminal() {
        super(TuebaTerminalSchema.instance);
    }

    
    public String getWord() {
        return (String) getSlot(TuebaTerminalSchema.IDX_word);
    }

    public void setWord(String val) {
        setSlot(TuebaTerminalSchema.IDX_word, val);
    }
    
    public String getCat() {
        return (String) getSlot(TuebaTerminalSchema.IDX_cat);
    }

    public void setCat(String val) {
        setSlot(TuebaTerminalSchema.IDX_cat, val);
    }
    
    public String getMorph() {
        return (String) getSlot(TuebaTerminalSchema.IDX_morph);
    }

    public void setMorph(String val) {
        setSlot(TuebaTerminalSchema.IDX_morph, val);
    }
    
    public String getLemma() {
        return (String) getSlot(TuebaTerminalSchema.IDX_lemma);
    }

    public void setLemma(String val) {
        setSlot(TuebaTerminalSchema.IDX_lemma, val);
    }
    
    public String getEdge_label() {
        return (String) getSlot(TuebaTerminalSchema.IDX_edge_label);
    }

    public void setEdge_label(String val) {
        setSlot(TuebaTerminalSchema.IDX_edge_label, val);
    }
    
    public TuebaNodeMarkable getParent() {
        return (TuebaNodeMarkable) getSlot(TuebaTerminalSchema.IDX_parent);
    }

    public void setParent(TuebaNodeMarkable val) {
        setSlot(TuebaTerminalSchema.IDX_parent, val);
    }
    
    public String getWsd_lexunits() {
        return (String) getSlot(TuebaTerminalSchema.IDX_wsd_lexunits);
    }

    public void setWsd_lexunits(String val) {
        setSlot(TuebaTerminalSchema.IDX_wsd_lexunits, val);
    }
    
    public String getWsd_comment() {
        return (String) getSlot(TuebaTerminalSchema.IDX_wsd_comment);
    }

    public void setWsd_comment(String val) {
        setSlot(TuebaTerminalSchema.IDX_wsd_comment, val);
    }
    
    public TuebaTerminal getSyn_parent() {
        return (TuebaTerminal) getSlot(TuebaTerminalSchema.IDX_syn_parent);
    }

    public void setSyn_parent(TuebaTerminal val) {
        setSlot(TuebaTerminalSchema.IDX_syn_parent, val);
    }
    
    public String getSyn_label() {
        return (String) getSlot(TuebaTerminalSchema.IDX_syn_label);
    }

    public void setSyn_label(String val) {
        setSlot(TuebaTerminalSchema.IDX_syn_label, val);
    }
    
    public String getComment() {
        return (String) getSlot(TuebaTerminalSchema.IDX_comment);
    }

    public void setComment(String val) {
        setSlot(TuebaTerminalSchema.IDX_comment, val);
    }
    
}