// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import exml.GenericMarkable;
import java.util.List;

public class TuebaNEMarkable extends GenericMarkable {
    public TuebaNEMarkable() {
        super(TuebaNESchema.instance);
    }
    public String getType() {
        return (String) getSlot(TuebaNESchema.IDX_type);
    }

    public void setType(String val) {
        setSlot(TuebaNESchema.IDX_type, val);
    }
}