// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import exml.objects.GenericObject;
import exml.objects.NamedObject;
import exml.annotations.MarkableSchema;

@MarkableSchema(TuebaSplitRelationSchema.class)
public class TuebaSplitRelationEdge extends GenericObject {
    public TuebaSplitRelationEdge() {
        super(TuebaSplitRelationSchema.instance.slotnames);
    }
    private String _type;
    private String _target;
    public String getType() {
        return _type;
    }

    public void setType(String val) {
        _type = val;
    }
    public String getTarget() {
        return _target;
    }

    public void setTarget(String val) {
        _target = val;
    }
}