// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import exml.GenericMarkable;
import java.util.List;

public class TuebaSentenceMarkable extends GenericMarkable {
    public TuebaSentenceMarkable() {
        super(TuebaSentenceSchema.instance);
    }
}