// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import elkfed.ml.util.Alphabet;
import exml.objects.GenericAccessor;
import exml.objects.GenericObjectFactory;
import exml.objects.ObjectSchema;
import exml.objects.StringConverter;

public class TuebaNESchema extends ObjectSchema<TuebaNEMarkable>
    {
        public static class TuebaNEFactory
          implements GenericObjectFactory<TuebaNEMarkable>
        {
            public TuebaNEMarkable createObject(ObjectSchema<TuebaNEMarkable> schema)
            {
                return new TuebaNEMarkable();
            }
        }
        public static TuebaNEFactory factory=new TuebaNEFactory();
        public static final Alphabet<String> global_alph=new Alphabet<String>();
        public static final int IDX_type=global_alph.lookupIndex("type");
        public static final TuebaNESchema instance=new TuebaNESchema();


        public TuebaNESchema() {
            super("ne",factory,global_alph);
            addAttribute("type", new StringConverter(),
                         new GenericAccessor<TuebaNEMarkable,String>(IDX_type));
        }

}