// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import exml.GenericMarkable;
import java.util.List;

public interface TuebaNodeInterface {

    String getXMLId();
    int getStart();
    int getEnd();
    TuebaNodeMarkable getParent();
    void setParent(TuebaNodeMarkable val);
    String getFunc();
    void setFunc(String val);
    public List<TuebaSecEdgeEdge> getSecEdge();
    public List<TuebaRelationEdge> getRelation();
}