// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import elkfed.ml.util.Alphabet;
import exml.objects.ObjectSchema;
import exml.objects.GenericObjectFactory;
import exml.objects.NamedObject;
import exml.objects.StringConverter;
import exml.objects.ReferenceConverter;
import exml.objects.GenericAccessor;

public class TuebaTerminalSchema extends ObjectSchema<TuebaTerminal>
    {
        public static class TuebaTerminalFactory
            implements GenericObjectFactory<TuebaTerminal>
        {
            public TuebaTerminal createObject(ObjectSchema<TuebaTerminal> schema)
            {
                return new TuebaTerminal();
            }
        }
        public static TuebaTerminalFactory factory=new TuebaTerminalFactory();

        public static final Alphabet<String> global_alph=new Alphabet<String>();
        
        public static final int IDX_word=global_alph.lookupIndex("form");
        
        public static final int IDX_cat=global_alph.lookupIndex("pos");
        
        public static final int IDX_morph=global_alph.lookupIndex("morph");
        
        public static final int IDX_lemma=global_alph.lookupIndex("lemma");
        
        public static final int IDX_edge_label=global_alph.lookupIndex("func");
        
        public static final int IDX_parent=global_alph.lookupIndex("parent");
        
        public static final int IDX_wsd_lexunits=global_alph.lookupIndex("wsd-lexunits");
        
        public static final int IDX_wsd_comment=global_alph.lookupIndex("wsd-comment");
        
        public static final int IDX_syn_parent=global_alph.lookupIndex("dephead");
        
        public static final int IDX_syn_label=global_alph.lookupIndex("deprel");
        
        public static final int IDX_comment=global_alph.lookupIndex("comment");
        

        public static final TuebaTerminalSchema instance=new TuebaTerminalSchema();
        public TuebaTerminalSchema() {
            super("word",factory,global_alph);
            addAttribute("form", new StringConverter(),
                         new GenericAccessor<TuebaTerminal,String>(IDX_word));
            addAttribute("pos", new StringConverter(),
                         new GenericAccessor<TuebaTerminal,String>(IDX_cat));
            addAttribute("morph", new StringConverter(),
                         new GenericAccessor<TuebaTerminal,String>(IDX_morph));
            addAttribute("lemma", new StringConverter(),
                         new GenericAccessor<TuebaTerminal,String>(IDX_lemma));
            addAttribute("func", new StringConverter(),
                         new GenericAccessor<TuebaTerminal,String>(IDX_edge_label));
            addAttribute("parent", new ReferenceConverter(),
                         new GenericAccessor<TuebaTerminal,TuebaNodeMarkable>(IDX_parent));
            addAttribute("wsd-lexunits", new StringConverter(),
                         new GenericAccessor<TuebaTerminal,String>(IDX_wsd_lexunits));
            addAttribute("wsd-comment", new StringConverter(),
                         new GenericAccessor<TuebaTerminal,String>(IDX_wsd_comment));
            addAttribute("dephead", new ReferenceConverter(),
                         new GenericAccessor<TuebaTerminal,TuebaTerminal>(IDX_syn_parent));
            addAttribute("deprel", new StringConverter(),
                         new GenericAccessor<TuebaTerminal,String>(IDX_syn_label));
            addAttribute("comment", new StringConverter(),
                         new GenericAccessor<TuebaTerminal,String>(IDX_comment));
        }

}