// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import exml.GenericMarkable;
import exml.annotations.EXMLAttribute;
import exml.annotations.MarkableSchema;
import java.util.List;

@MarkableSchema(TuebaSentenceSchema.class)
public class TuebaSentenceMarkable extends GenericMarkable
{
    public TuebaSentenceMarkable() {
        super(TuebaSentenceSchema.instance);
    }
}