// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import elkfed.ml.util.Alphabet;
import exml.objects.ObjectSchema;
import exml.objects.NamedObject;
import exml.objects.GenericObjectFactory;
import exml.objects.StringConverter;
import exml.objects.ReferenceConverter;
import exml.objects.GenericAccessor;

public class TuebaSplitRelationSchema extends ObjectSchema<TuebaSplitRelationEdge>
    {
        public static class TuebaSplitRelationFactory
          implements GenericObjectFactory<TuebaSplitRelationEdge>
        {
            public TuebaSplitRelationEdge createObject(ObjectSchema<TuebaSplitRelationEdge> schema)
            {
                return new TuebaSplitRelationEdge();
            }
        }
        public static TuebaSplitRelationFactory factory=new TuebaSplitRelationFactory();
        public static final Alphabet<String> global_alph=new Alphabet<String>();
        public static final int IDX_type=global_alph.lookupIndex("type");
        public static final int IDX_target=global_alph.lookupIndex("target");
        public static final TuebaSplitRelationSchema instance=new TuebaSplitRelationSchema();


        public TuebaSplitRelationSchema() {
            super("splitRelation",factory,global_alph);
            addAttribute("type", new StringConverter(),
                         new GenericAccessor<TuebaSplitRelationEdge,String>(IDX_type));
            addAttribute("target", new StringConverter(),
                         new GenericAccessor<TuebaSplitRelationEdge,String>(IDX_target));
        }

}