// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import exml.GenericMarkable;

public class TuebaEduMarkable extends GenericMarkable {
    public TuebaEduMarkable() {
        super(TuebaEduSchema.instance);
    }
}