// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import exml.GenericMarkable;
import exml.annotations.Attribute;
import exml.annotations.MarkableSchema;
import java.util.List;

@MarkableSchema(TuebaTextSchema.class)
public class TuebaTextMarkable extends GenericMarkable
{
    public TuebaTextMarkable() {
        super(TuebaTextSchema.instance);
    }
    private String _origin;
    @Attribute("origin")
    public String getOrigin() {
        return _origin;
    }

    public void setOrigin(String val) {
       _origin = val;
    }
}