// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import exml.GenericMarkable;
import exml.annotations.EXMLAttribute;
import exml.annotations.MarkableSchema;
import java.util.List;
import exml.objects.NamedObject;
import java.util.List;

@MarkableSchema(TuebaNodeSchema.class)
public class TuebaNodeMarkable extends GenericMarkable
  implements TuebaNodeInterface
{
    public TuebaNodeMarkable() {
        super(TuebaNodeSchema.instance);
    }
    private String _cat;
    private String _edge_label;
    private TuebaNodeMarkable _parent;
    private String _comment;
    @EXMLAttribute("cat")
    public String getCat() {
        return _cat;
    }

    public void setCat(String val) {
       _cat = val;
    }
    @EXMLAttribute("func")
    public String getEdge_label() {
        return _edge_label;
    }

    public void setEdge_label(String val) {
       _edge_label = val;
    }
    @EXMLAttribute("parent")
    public TuebaNodeMarkable getParent() {
        return _parent;
    }

    public void setParent(TuebaNodeMarkable val) {
       _parent = val;
    }
    @EXMLAttribute("comment")
    public String getComment() {
        return _comment;
    }

    public void setComment(String val) {
       _comment = val;
    }
    public List<NamedObject> getChildren() {
        return (List<NamedObject>) getSlot(TuebaNodeSchema.IDX_children);
    }

    public void setChildren(List<NamedObject> val) {
        setSlot(TuebaNodeSchema.IDX_children, val);
    }
    public List<TuebaSecEdgeEdge> getSecEdge() {
      List<TuebaSecEdgeEdge> lst = (List<TuebaSecEdgeEdge>) getSlot(TuebaNodeSchema.IDX_secEdge);
      return lst;
    }
    public List<TuebaRelationEdge> getRelation() {
      List<TuebaRelationEdge> lst = (List<TuebaRelationEdge>) getSlot(TuebaNodeSchema.IDX_relation);
      return lst;
    }
    public List<TuebaSplitRelationEdge> getSplitRelation() {
      List<TuebaSplitRelationEdge> lst = (List<TuebaSplitRelationEdge>) getSlot(TuebaNodeSchema.IDX_splitRelation);
      return lst;
    }
}