// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import elkfed.ml.util.Alphabet;
import exml.objects.ObjectSchema;
import exml.objects.NamedObject;
import exml.objects.GenericObjectFactory;
import exml.objects.StringConverter;
import exml.objects.ReferenceConverter;
import exml.objects.GenericAccessor;
import exml.objects.IAccessor;

public class TuebaConnectiveSchema extends ObjectSchema<TuebaConnectiveEdge>
    {
        public static class TuebaConnectiveFactory
          implements GenericObjectFactory<TuebaConnectiveEdge>
        {
            public TuebaConnectiveEdge createObject(ObjectSchema<TuebaConnectiveEdge> schema)
            {
                return new TuebaConnectiveEdge();
            }
        }
        public static TuebaConnectiveFactory factory=new TuebaConnectiveFactory();
        public static final Alphabet<String> global_alph=new Alphabet<String>();
        public static final TuebaConnectiveSchema instance=new TuebaConnectiveSchema();


        public TuebaConnectiveSchema() {
            super("connective", TuebaConnectiveEdge.class,
                  factory, global_alph);
            addAttribute("konn", new StringConverter(),
                new IAccessor<TuebaConnectiveEdge, String>() {
                    public String get(TuebaConnectiveEdge o) {
                       return o.getKonn(); }
                    public void put(TuebaConnectiveEdge o, String v) {
                       o.setKonn(v); }});
            addAttribute("rel1", new StringConverter(),
                new IAccessor<TuebaConnectiveEdge, String>() {
                    public String get(TuebaConnectiveEdge o) {
                       return o.getRel1(); }
                    public void put(TuebaConnectiveEdge o, String v) {
                       o.setRel1(v); }});
            addAttribute("rel2", new StringConverter(),
                new IAccessor<TuebaConnectiveEdge, String>() {
                    public String get(TuebaConnectiveEdge o) {
                       return o.getRel2(); }
                    public void put(TuebaConnectiveEdge o, String v) {
                       o.setRel2(v); }});
        }
}