// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import exml.GenericMarkable;

public class TuebaTextMarkable extends GenericMarkable {
    public TuebaTextMarkable() {
        super(TuebaTextSchema.instance);
    }
    public String getOrigin() {
        return (String) getSlot(TuebaTextSchema.IDX_origin);
    }

    public void setOrigin(String val) {
        setSlot(TuebaTextSchema.IDX_origin, val);
    }
}