// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import elkfed.ml.util.Alphabet;
import exml.objects.ObjectSchema;
import exml.objects.NamedObject;
import exml.objects.GenericObjectFactory;
import exml.objects.StringConverter;
import exml.objects.ReferenceConverter;
import exml.objects.GenericAccessor;
import exml.objects.IAccessor;

public class TuebaDiscRelSchema extends ObjectSchema<TuebaDiscRelEdge>
    {
        public static class TuebaDiscRelFactory
          implements GenericObjectFactory<TuebaDiscRelEdge>
        {
            public TuebaDiscRelEdge createObject(ObjectSchema<TuebaDiscRelEdge> schema)
            {
                return new TuebaDiscRelEdge();
            }
        }
        public static TuebaDiscRelFactory factory=new TuebaDiscRelFactory();
        public static final Alphabet<String> global_alph=new Alphabet<String>();
        public static final TuebaDiscRelSchema instance=new TuebaDiscRelSchema();


        public TuebaDiscRelSchema() {
            super("discRel", TuebaDiscRelEdge.class,
                  factory, global_alph);
            addAttribute("relation", new StringConverter(),
                new IAccessor<TuebaDiscRelEdge, String>() {
                    public String get(TuebaDiscRelEdge o) {
                       return o.getRelation(); }
                    public void put(TuebaDiscRelEdge o, String v) {
                       o.setRelation(v); }});
            addAttribute("marking", new StringConverter(),
                new IAccessor<TuebaDiscRelEdge, String>() {
                    public String get(TuebaDiscRelEdge o) {
                       return o.getMarking(); }
                    public void put(TuebaDiscRelEdge o, String v) {
                       o.setMarking(v); }});
            addAttribute("arg2", new ReferenceConverter(),
                new IAccessor<TuebaDiscRelEdge, NamedObject>() {
                    public NamedObject get(TuebaDiscRelEdge o) {
                       return o.getArg2(); }
                    public void put(TuebaDiscRelEdge o, NamedObject v) {
                       o.setArg2(v); }});
        }
}