// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import elkfed.ml.util.Alphabet;
import exml.objects.ObjectSchema;
import exml.objects.NamedObject;
import exml.objects.GenericObjectFactory;
import exml.objects.StringConverter;
import exml.objects.ReferenceConverter;
import exml.objects.GenericAccessor;
import exml.objects.IAccessor;

public class TuebaRelationSchema extends ObjectSchema<TuebaRelationEdge>
    {
        public static class TuebaRelationFactory
          implements GenericObjectFactory<TuebaRelationEdge>
        {
            public TuebaRelationEdge createObject(ObjectSchema<TuebaRelationEdge> schema)
            {
                return new TuebaRelationEdge();
            }
        }
        public static TuebaRelationFactory factory=new TuebaRelationFactory();
        public static final Alphabet<String> global_alph=new Alphabet<String>();
        public static final TuebaRelationSchema instance=new TuebaRelationSchema();


        public TuebaRelationSchema() {
            super("relation", TuebaRelationEdge.class,
                  factory, global_alph);
            addAttribute("type", new StringConverter(),
                new IAccessor<TuebaRelationEdge, String>() {
                    public String get(TuebaRelationEdge o) {
                       return o.getType(); }
                    public void put(TuebaRelationEdge o, String v) {
                       o.setType(v); }});
            addAttribute("target", new ReferenceConverter(),
                new IAccessor<TuebaRelationEdge, TuebaNodeInterface>() {
                    public TuebaNodeInterface get(TuebaRelationEdge o) {
                       return o.getTarget(); }
                    public void put(TuebaRelationEdge o, TuebaNodeInterface v) {
                       o.setTarget(v); }});
        }
}