// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import exml.objects.GenericObject;
import exml.objects.NamedObject;

public class TuebaSecEdgeEdge extends GenericObject {
    public TuebaSecEdgeEdge() {
        super(TuebaSecEdgeSchema.instance.slotnames);
    }
    public String getCat() {
        return (String) getSlot(TuebaSecEdgeSchema.IDX_cat);
    }

    public void setCat(String val) {
        setSlot(TuebaSecEdgeSchema.IDX_cat, val);
    }
    public NamedObject getParent() {
        return (NamedObject) getSlot(TuebaSecEdgeSchema.IDX_parent);
    }

    public void setParent(NamedObject val) {
        setSlot(TuebaSecEdgeSchema.IDX_parent, val);
    }
}