// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import exml.GenericMarkable;
import exml.annotations.EXMLAttribute;
import exml.annotations.MarkableSchema;
import java.util.List;

@MarkableSchema(TuebaEduRangeSchema.class)
public class TuebaEduRangeMarkable extends GenericMarkable
{
    public TuebaEduRangeMarkable() {
        super(TuebaEduRangeSchema.instance);
    }
    public List<TuebaDiscRelEdge> getDiscRel() {
      List<TuebaDiscRelEdge> lst = (List<TuebaDiscRelEdge>) getSlot(TuebaEduRangeSchema.IDX_discRel);
      return lst;
    }
}