// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import exml.objects.GenericObject;
import exml.objects.NamedObject;

public class TuebaDiscRelEdge extends GenericObject {
    public TuebaDiscRelEdge() {
        super(TuebaDiscRelSchema.instance.slotnames);
    }
    public String getRelation() {
        return (String) getSlot(TuebaDiscRelSchema.IDX_relation);
    }

    public void setRelation(String val) {
        setSlot(TuebaDiscRelSchema.IDX_relation, val);
    }
    public String getMarking() {
        return (String) getSlot(TuebaDiscRelSchema.IDX_marking);
    }

    public void setMarking(String val) {
        setSlot(TuebaDiscRelSchema.IDX_marking, val);
    }
    public NamedObject getArg2() {
        return (NamedObject) getSlot(TuebaDiscRelSchema.IDX_arg2);
    }

    public void setArg2(NamedObject val) {
        setSlot(TuebaDiscRelSchema.IDX_arg2, val);
    }
}