// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import elkfed.ml.util.Alphabet;
import exml.objects.*;

public class TuebaConnectiveSchema extends ObjectSchema<TuebaConnectiveEdge>
    {
        public static GenericObjectFactory<TuebaConnectiveEdge> factory=
                (schema) -> new TuebaConnectiveEdge();
        public static final Alphabet<String> global_alph=new Alphabet<String>();
        public static final Attribute<TuebaConnectiveEdge, String> ATTR_konn = new Attribute<TuebaConnectiveEdge, String> ("konn",
                new IAccessor<TuebaConnectiveEdge, String>() {
                    public String get(TuebaConnectiveEdge o) {
                       return o.getKonn(); }
                    public void put(TuebaConnectiveEdge o, String v) {
                       o.setKonn(v); }},
                new StringConverter());
        public static final Attribute<TuebaConnectiveEdge, String> ATTR_rel1 = new Attribute<TuebaConnectiveEdge, String> ("rel1",
                new IAccessor<TuebaConnectiveEdge, String>() {
                    public String get(TuebaConnectiveEdge o) {
                       return o.getRel1(); }
                    public void put(TuebaConnectiveEdge o, String v) {
                       o.setRel1(v); }},
                new EnumConverter());
        public static final Attribute<TuebaConnectiveEdge, String> ATTR_rel2 = new Attribute<TuebaConnectiveEdge, String> ("rel2",
                new IAccessor<TuebaConnectiveEdge, String>() {
                    public String get(TuebaConnectiveEdge o) {
                       return o.getRel2(); }
                    public void put(TuebaConnectiveEdge o, String v) {
                       o.setRel2(v); }},
                new EnumConverter());
        public static final TuebaConnectiveSchema instance=new TuebaConnectiveSchema();


        public TuebaConnectiveSchema() {
            super("connective", TuebaConnectiveEdge.class,
                  factory, global_alph);
            addAttribute(ATTR_konn);
            addAttribute(ATTR_rel1);
            addAttribute(ATTR_rel2);
        }
}