// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import elkfed.ml.util.Alphabet;
import exml.objects.GenericAccessor;
import exml.objects.GenericObjectFactory;
import exml.objects.NamedObject;
import exml.objects.ObjectSchema;
import exml.objects.ReferenceConverter;
import exml.objects.StringConverter;

public class TuebaDiscRelSchema extends ObjectSchema<TuebaDiscRelEdge>
    {
        public static class TuebaDiscRelFactory
          implements GenericObjectFactory<TuebaDiscRelEdge>
        {
            public TuebaDiscRelEdge createObject(ObjectSchema<TuebaDiscRelEdge> schema)
            {
                return new TuebaDiscRelEdge();
            }
        }
        public static TuebaDiscRelFactory factory=new TuebaDiscRelFactory();
        public static final Alphabet<String> global_alph=new Alphabet<String>();
        public static final int IDX_relation=global_alph.lookupIndex("relation");
        public static final int IDX_marking=global_alph.lookupIndex("marking");
        public static final int IDX_arg2=global_alph.lookupIndex("arg2");
        public static final TuebaDiscRelSchema instance=new TuebaDiscRelSchema();


        public TuebaDiscRelSchema() {
            super("discRel",factory,global_alph);
            addAttribute("relation", new StringConverter(),
                         new GenericAccessor<TuebaDiscRelEdge,String>(IDX_relation));
            addAttribute("marking", new StringConverter(),
                         new GenericAccessor<TuebaDiscRelEdge,String>(IDX_marking));
            addAttribute("arg2", new ReferenceConverter<NamedObject>(),
                         new GenericAccessor<TuebaDiscRelEdge,NamedObject>(IDX_arg2));
        }

}