// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import java.util.List;

import exml.GenericMarkable;
import exml.objects.NamedObject;

public class TuebaNodeMarkable extends GenericMarkable {
    public TuebaNodeMarkable() {
        super(TuebaNodeSchema.instance);
    }
    public String getCat() {
        return (String) getSlot(TuebaNodeSchema.IDX_cat);
    }

    public void setCat(String val) {
        setSlot(TuebaNodeSchema.IDX_cat, val);
    }
    public String getFunc() {
        return (String) getSlot(TuebaNodeSchema.IDX_func);
    }

    public void setFunc(String val) {
        setSlot(TuebaNodeSchema.IDX_func, val);
    }
    public TuebaNodeMarkable getParent() {
        return (TuebaNodeMarkable) getSlot(TuebaNodeSchema.IDX_parent);
    }

    public void setParent(TuebaNodeMarkable val) {
        setSlot(TuebaNodeSchema.IDX_parent, val);
    }
    public String getComment() {
        return (String) getSlot(TuebaNodeSchema.IDX_comment);
    }

    public void setComment(String val) {
        setSlot(TuebaNodeSchema.IDX_comment, val);
    }
    public List<NamedObject> getChildren() {
        return (List<NamedObject>) getSlot(TuebaNodeSchema.IDX_children);
    }

    public void setChildren(List<NamedObject> val) {
        setSlot(TuebaNodeSchema.IDX_children, val);
    }
}