// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import elkfed.ml.util.Alphabet;
import exml.objects.ObjectSchema;
import exml.objects.NamedObject;
import exml.objects.GenericObjectFactory;
import exml.objects.StringConverter;
import exml.objects.ReferenceConverter;
import exml.objects.GenericAccessor;
import exml.objects.IAccessor;

public class TuebaSecEdgeSchema extends ObjectSchema<TuebaSecEdgeEdge>
    {
        public static class TuebaSecEdgeFactory
          implements GenericObjectFactory<TuebaSecEdgeEdge>
        {
            public TuebaSecEdgeEdge createObject(ObjectSchema<TuebaSecEdgeEdge> schema)
            {
                return new TuebaSecEdgeEdge();
            }
        }
        public static TuebaSecEdgeFactory factory=new TuebaSecEdgeFactory();
        public static final Alphabet<String> global_alph=new Alphabet<String>();
        public static final TuebaSecEdgeSchema instance=new TuebaSecEdgeSchema();


        public TuebaSecEdgeSchema() {
            super("secEdge", TuebaSecEdgeEdge.class,
                  factory, global_alph);
            addAttribute("cat", new StringConverter(),
                new IAccessor<TuebaSecEdgeEdge, String>() {
                    public String get(TuebaSecEdgeEdge o) {
                       return o.getCat(); }
                    public void put(TuebaSecEdgeEdge o, String v) {
                       o.setCat(v); }});
            addAttribute("parent", new ReferenceConverter(),
                new IAccessor<TuebaSecEdgeEdge, TuebaNodeInterface>() {
                    public TuebaNodeInterface get(TuebaSecEdgeEdge o) {
                       return o.getParent(); }
                    public void put(TuebaSecEdgeEdge o, TuebaNodeInterface v) {
                       o.setParent(v); }});
        }
}