// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import exml.GenericMarkable;

public class TuebaEduRangeMarkable extends GenericMarkable {
    public TuebaEduRangeMarkable() {
        super(TuebaEduRangeSchema.instance);
    }
}