// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import elkfed.ml.util.Alphabet;
import exml.objects.GenericAccessor;
import exml.objects.GenericObjectFactory;
import exml.objects.ObjectSchema;
import exml.objects.ReferenceConverter;
import exml.objects.StringConverter;

public class TuebaNodeSchema extends ObjectSchema<TuebaNodeMarkable>
    {
        public static class TuebaNodeFactory
          implements GenericObjectFactory<TuebaNodeMarkable>
        {
            public TuebaNodeMarkable createObject(ObjectSchema<TuebaNodeMarkable> schema)
            {
                return new TuebaNodeMarkable();
            }
        }
        public static TuebaNodeFactory factory=new TuebaNodeFactory();
        public static final Alphabet<String> global_alph=new Alphabet<String>();
        public static final int IDX_cat=global_alph.lookupIndex("cat");
        public static final int IDX_func=global_alph.lookupIndex("func");
        public static final int IDX_parent=global_alph.lookupIndex("parent");
        public static final int IDX_comment=global_alph.lookupIndex("comment");
        public static final int IDX_children=global_alph.lookupIndex("children");
        public static final int IDX_secEdge=global_alph.lookupIndex("secEdge");
        public static final int IDX_relation=global_alph.lookupIndex("relation");
        public static final int IDX_splitRelation=global_alph.lookupIndex("splitRelation");
        public static final TuebaNodeSchema instance=new TuebaNodeSchema();


        public TuebaNodeSchema() {
            super("node",factory,global_alph);
            addAttribute("cat", new StringConverter(),
                         new GenericAccessor<TuebaNodeMarkable,String>(IDX_cat));
            addAttribute("func", new StringConverter(),
                         new GenericAccessor<TuebaNodeMarkable,String>(IDX_func));
            addAttribute("parent", new ReferenceConverter(),
                         new GenericAccessor<TuebaNodeMarkable,TuebaNodeMarkable>(IDX_parent));
            addAttribute("comment", new StringConverter(),
                         new GenericAccessor<TuebaNodeMarkable,String>(IDX_comment));
            addRelation("secEdge", TuebaSecEdgeSchema.instance);
            addRelation("relation", TuebaRelationSchema.instance);
            addRelation("splitRelation", TuebaSplitRelationSchema.instance);
        }

}