// -*- mode: java -*-
// This is code generated by gen_code.py from the EXML schema

package exml.tueba;
import elkfed.ml.util.Alphabet;
import exml.objects.GenericAccessor;
import exml.objects.GenericObjectFactory;
import exml.objects.NamedObject;
import exml.objects.ObjectSchema;
import exml.objects.ReferenceConverter;
import exml.objects.StringConverter;

public class TuebaRelationSchema extends ObjectSchema<TuebaRelationEdge>
    {
        public static class TuebaRelationFactory
          implements GenericObjectFactory<TuebaRelationEdge>
        {
            public TuebaRelationEdge createObject(ObjectSchema<TuebaRelationEdge> schema)
            {
                return new TuebaRelationEdge();
            }
        }
        public static TuebaRelationFactory factory=new TuebaRelationFactory();
        public static final Alphabet<String> global_alph=new Alphabet<String>();
        public static final int IDX_type=global_alph.lookupIndex("type");
        public static final int IDX_target=global_alph.lookupIndex("target");
        public static final TuebaRelationSchema instance=new TuebaRelationSchema();


        public TuebaRelationSchema() {
            super("relation",factory,global_alph);
            addAttribute("type", new StringConverter(),
                         new GenericAccessor<TuebaRelationEdge,String>(IDX_type));
            addAttribute("target", new ReferenceConverter(),
                         new GenericAccessor<TuebaRelationEdge,NamedObject>(IDX_target));
        }

}